apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: telegram-serverless
  labels:
    app: zookeeper
    component: messaging
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: zookeeper
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: server
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: leader-election
    port: 3888
    targetPort: 3888
    protocol: TCP
