apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: telegram-serverless
  labels:
    app: redis
    component: storage
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
